### ISSUE TITLE
Great Work ! But...

### ISSUE THREAD

**Issue by Steepy12** [TheLtWilson/wave-link-key-wrapper#2]
It's very good work, the code is well done and easy to understand, and it is the only code that offers an alternative to the SDK made by the community which is now abandoned, the only downside is that in your code you do not offer all the functions that we can have, such as changing the volume of the browser on the local or the stream (but you detect it which is already great!) another "negative" point is that a small wiki is missing which could help a lot to understand how the Wavelink Websocket works, if I had not tested your raw code I would not have understood that Wavelink uses an "indentifer" and the "name" to manage a audio output, I think fixing these two little things would make it a great base for anyone wanting to develop things with the WaveLink wbesocket ! And also the repos is pretty active for a small project like that so it's nice too :D

**Comment by TheLtWilson** [comment]
I was actually planning to create a separate repo purely dedicated to controlling and managing Wave Link that you could install with pip. It's just that I've never written a public library that would be used by other people. So we'll see if that ever happens.

But yeah, this repo is just a personal project so that I could easily restore this on my computer if I ever need to reinstall Windows. It being helpful to other people is just a bonus.

As for the features you mentioned, I'll look into adding them whenever I get the chance :3

**Comment by TheLtWilson** [comment]
Setting an input's volume and mute is now available as of commit 9cfc2f2 with the `set_input_volume()` and `set_input_mute()` functions. I've also added a very basic rundown of generic functions in the README file as of the `6ae918b` commit - I might extend documentation later but I'd rather have that for a dedicated Wave Link library.

**Comment by Steepy12** [comment]
> Setting an input's volume and mute is now available as of commit 9cfc2f2 with the `set_input_volume()` and `set_input_mute()` functions. I've also added a very basic rundown of generic functions in the README file as of the `6ae918b` commit - I might extend documentation later but I'd rather have that for a dedicated Wave Link library.

Fantastic! thanks a lot! when i've finished my current dev job I might look making a fork with your code in order to make a proper library if you're okay with it (with you as a contributor of course)

**Comment by TheLtWilson** [comment]
feel free to do whatever you want with the code. thats the beauty of open source. i added the MIT license to the project just to make sure it's clear that i'm ok with people doing whatever they want with it.

**Comment by Steepy12** [comment]
> feel free to do whatever you want with the code. thats the beauty of open source. i added the MIT license to the project just to make sure it's clear that i'm ok with people doing whatever they want with it.

Thank's Forgot to make a fork but i've made a Lib here : https://github.com/Steepy12/ElgatoWavePy and also available to download with "pip install ElgatoWavePy"
